export const BRAND_LOGO_DOMAINS: Record<string, string> = {
  CRCLx: 'circle.com',
  SPYx: 'spglobal.com',
  MSTRx: 'strategy.com',
  QQQx: 'invesco.com',
  STRCx: 'strategy.com',
  GLDx: 'ssga.com',
  AAPLx: 'apple.com',
  TSLAx: 'tesla.com',
  NVDAx: 'nvidia.com',
  COINx: 'coinbase.com',
  HOODx: 'robinhood.com',
  AMZNx: 'amazon.com',
  GMEx: 'gamestop.com',
  GOOGLx: 'google.com',
  MSFTx: 'microsoft.com',
  PLTRx: 'palantir.com',
  MCDx: 'mcdonalds.com',
  SPCXx: 'spacex.com',
  METAx: 'meta.com',
  'BRK.Bx': 'berkshirehathaway.com',
  INTCx: 'intel.com',
  AVGOx: 'broadcom.com',
  DFDVx: 'defidevcorp.com',
  MRVLx: 'marvell.com',
  ORCLx: 'oracle.com',
  KOx: 'coca-colacompany.com',
  NFLXx: 'netflix.com',
  AMDx: 'amd.com',
  PEPx: 'pepsico.com',
  XOMx: 'corporate.exxonmobil.com',
  TQQQx: 'proshares.com',
  BMNRx: 'bitminetech.io',
  PGx: 'pg.com',
  Vx: 'visa.com',
  CRMx: 'salesforce.com',
  MUx: 'micron.com',
  JPMx: 'jpmorganchase.com',
  WMTx: 'walmart.com',
  TMOx: 'thermofisher.com',
  PFEx: 'pfizer.com',
  CMCSAx: 'corporate.comcast.com',
  UNHx: 'unitedhealthgroup.com',
};

export function brandLogoUrl(symbol: string, fallback: string) {
  const domain = BRAND_LOGO_DOMAINS[symbol];
  return domain ? `https://www.google.com/s2/favicons?domain=${encodeURIComponent(domain)}&sz=128` : fallback;
}
